---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gce-disk-pv1
  labels: 
    disk: pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: default
  gcePersistentDisk:
    pdName: gce-disk
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gce-disk-pv2
  labels: 
    disk: pv2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: default
  gcePersistentDisk:
    pdName: gce-disk
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gce-disk-pv3
  labels: 
    disk: pv3
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: default
  gcePersistentDisk:
    pdName: gce-disk
    fsType: ext4