apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: web
    name: kub-m
  name: kub-m
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
        - name: kub-py
          image: msrn/kub:v7
          env:
            - name: "REDIS_HOST"
              value: "localhost"
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
        - name: redis
          image: docker.io/redis
          ports:
            - containerPort: 6379
              protocol: TCP

