apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kub
    name: kub
  name: kub
  selfLink: /api/v1/namespaces/default/services/kub
spec:
  clusterIP: <unknown>
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: kub
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
